### ISSUE TITLE
wrong variable

### ISSUE THREAD

**Issue by cavet** [oda-hub/dispatcher-chart#1]
`- name: data-reduced-ddcache
        hostPath:
          path:  {{ .Values.data.reduced.ddcache }}`

=> 
`- name: data-reduced-ddcache
        hostPath:
          path: {{ .Values.oda.ddcache }}`

**Comment by volodymyrss** [comment]
I assign to Denys since he likely experienced, fixed,or circumvented this already

**Comment by dsavchenko** [comment]
I circumvented this by using PVCs. Changed to consistent .Values.oda.ddcache by #7
