### ISSUE TITLE
missing file: dispatcher/conf/conf_env.yml

### ISSUE THREAD

**Issue by cavet** [oda-hub/dispatcher-chart#2]
Pod log:
MountVolume.SetUp failed for volume "dispatcher-conf" : secret "dispatcher-conf" not found

make.sh:
kubectl create secret generic dispatcher-conf --from-file=conf_env.yml=dispatcher/conf/conf_env.yml

**Comment by volodymyrss** [comment]
This file contains information which need to be filled. 
It can be copied from here and adopted: https://github.com/oda-hub/dispatcher-app/blob/staging-1-3/cdci_data_analysis/config_dir/conf_env.yml

But I added an adopted example there https://github.com/oda-hub/dispatcher-chart/blob/master/conf/conf_env.yml.example

**Comment by volodymyrss** [comment]
the explanation and commits given in the last comment should be resolve it. I should have closed this before.
